arch: NestedUNet
batch_size: 8
dataset: '0420'
deep_supervision: false
early_stopping: -1
epochs: 300
factor: 0.1
gamma: 0.6666666666666666
img_ext: .jpg
input_channels: 3
input_h: 512
input_w: 512
load_split: false
loss: BCEDiceLoss
lr: 0.001
mask_ext: .png
milestones: 1,2
min_lr: 1.0e-05
momentum: 0.9
name: 0420_lung_NestedUNet_BCEDiceLoss_woDS
nesterov: false
num_classes: 1
num_workers: 4
optimizer: SGD
patience: 10
predict: false
save_split: false
scheduler: CosineAnnealingLR
seg_img: seg_img
sub_dataset: lung
test: false
train: true
two_step_test: false
weight_decay: 0.0001
